server:
  port: 8763
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: spring-msg-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/